[build]
  publish = ""
  functions = "netlify/functions"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
