[build]
  functions = "netlify/functions"
  publish = ""
  # command = "npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações específicas para funções
[functions]
  node_bundler = "esbuild"